server:
  port: 8087
  #Tomcat调优
  tomcat:
    # 最大线程数
    max-threads: 500
    # 队列长度
    accept-count: 50
    # 最大链接数
    max-connections: 8192
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/miaosha?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 20 # 初始化大小、最小、最大连接数
      min-idle: 10
      max-active: 200
      max-wait: 2000 # 配置获取连接等待超时的时间
      stat-view-servlet:
        log                                                                                                                                                                                                                                                                              in-username: admin
        login-password: admin
        enabled: false #是否启用StatViewServlet（监控页面）默认值为false
      filter:
        stat: # 配置 StatFilter
          log-slow-sql: true
          slow-sql-millis: 2000
  #设置null的属性值不显示，比如通过json返回User的时候，密码要设置为null
  jackson:
    default-property-inclusion: non_null

# mybatis
# 实体类包路径
mybatis:
  type-aliases-package: cn.peoplevip.miaosha.domain
  configuration:
    map-underscore-to-camel-case: true #下划线转驼峰
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:cn/peoplevip/miaosha/dao/*.xml


redis:
  StorageType: byte #redis存储方式是字符还是二进制，参数可选 string、byte
  host: 127.0.0.1
  poolMaxTotal: 10
  poolMaxWait: 5000
  poolMaxldle: 10
  port: 6379
  timeout: 3

# 前端地址(适合前后端分离项目),解决跨域问题
frontEndHost: http://localhost:8081
#AES 密钥,这里要和网关的秘钥统一
aespass: bc@9EFSceq


